### PR TITLE
Use `carton` instead of webpack.js, update JSKit

### LINKED ISSUE #5: LifeGameWeb.wasm not found
Hey there! I was looking to get this example up and running and I have had a couple of issues.

The first one I was able to resolve, but thought I would point it out if others are having the same issue:
```
ERROR in Entry module not found: Error: Can't resolve '/Users/aaronjedwards/Downloads/life-game-with-swiftwasm-master/static' in '/Users/aaronjedwards/Downloads/life-game-with-swiftwasm-master'
```
The `HtmlWebpackPlugin` was only pointing to the root of the directory where the HTML template was stored instead of the template file itself so I changed the plugin instance in `webpack.config.js` to:

```js
...
new HtmlWebpackPlugin({
      template: staticPath + "/index.html",
 }),
...
```

And that fixed my first issue!

But even though everything builds properly now, I am getting a 404 in browser when looking for `LifeGameWeb.wasm`, as if its not actually output from the build process.

Is there a build step missing in your instructions or something that I am not understanding? Any help is appreciated!

### PR DESCRIPTION
**Pull request by MaxDesiatov**
`swiftenv`, Node.js and webpack.js are no longer required, which I think makes the installation and build instructions simpler.

Also, the JavaScriptKit version is updated and its version is now specified directly instead of its revision in `Package.swift`.

Resolves #5.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
I don't have access to netlify, so I'm not sure how to fix CI for this PR 🤔

**Comment by aaronjedwards** [comment]
@MaxDesiatov Experiencing the following issue. Is there way to get around this error?

`the target 'JavaScriptKit' in product 'JavaScriptKit' contains unsafe build flags`

Edit: The build succeeds via carton but I cant build in Xcode and there is no autocompletion

**Comment by MaxDesiatov** [comment]
Do I understand correctly that this error is only reproducible with Xcode for you?

To my knowledge Xcode doesn't and won't support cross-compiling to non-Apple platforms. I don't think we can do anything about that due to the way it's designed and due its closed-source nature. See https://github.com/TokamakUI/Tokamak/issues/216 for more details.

I personally recommend using VSCode, but I know there's a rich ecosystem of other editors and IDEs (excluding Xcode obviously) that could work just as well.

**Comment by aaronjedwards** [comment]
@MaxDesiatov Per TokamakUI/Tokamak#216 there was still some problems with getting SourceKit-LSP working with VS Code and wasm. Is that still the case?

**Comment by MaxDesiatov** [comment]
Yes, it is, but at least there's a known path forward and it all depends on our efforts. There's nothing we can do to fix Xcode I'm afraid. I'll file something at bugs.swift.org later today.

**Comment by kateinoigakukun** [comment]
Thanks for the fix and proposing carton! I'm not sure how to produce index.html and packed js from carton. Does carton support that feature?

**Comment by MaxDesiatov** [comment]
Not yet, but I'll add it in the next version.

**Comment by kateinoigakukun** [comment]
Sorry, I think it's early to use carton until the deployment feature will be implemented. I'm looking forward to it.

**Comment by MaxDesiatov** [comment]
No problem, would you mind if the PR stays open until then?

**Comment by kateinoigakukun** [comment]
No, no problem. At this time, Could you cherry-pick the changes related to JSKit upgrade?

**Comment by kateinoigakukun** [comment]
I updated this project to use carton and now deployed on GItHub Pages

**Pull request closed without merging**
